### ISSUE TITLE
Missing census data

### ISSUE THREAD

**Issue by rodionos** [cestastanford/historical-us-city-populations#4]
I noticed a fair number of zeros for city population sizes covering the years when such data should be available from U.S. census. Consider Clinton, UT example. It should have 1,768 but has 0 instead. What could explain the difference?

https://en.wikipedia.org/wiki/Clinton,_Utah

**Comment by hepplerj** [comment]
The dataset is compiled from many sources and sometimes things are overlooked. Feel free to submit a pull request with the missing data and we'll take a look!

**Comment by rodionos** [comment]
I only did a few manual checks. Those inconsistencies are not worth a PR. For a more holistic test coverage, I'm planning on loading census data from the American fact finder and then scan for missing data. Thx.

**Comment by hepplerj** [comment]
@rodionos Can I ask, is it mostly more recent years where you're finding the missing or inconsistent data?

**Comment by rodionos** [comment]
Yes, 1970 onwards. I just noticed quite a few cities with zero population for 1970 which was the census year. I checked a few of them online, which means wikipedia, and they had valid data for 1970.
